replicaCount: 1
image:
  repository: ghcr.io/capadil/sandboxservice
  tag: 6644e06a96a073824751d9de8562e4e6be8f4de5
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080
env:
  APP_VERSION: K8s-dev-helm-2.0.1
  ASPNETCORE_URLS: http://+:8080
